---
- name: check if origin dir exists
  stat: path=/data/origin
  register: origin_dir

- name: sync local origin repo
  synchronize:
    src: "{{ local_origin_path }}"
    dest: "/data"
    recursive: yes
  when: origin_dir.stat.exists == False

- name: Check for openshift binaries in /data/origin/_output
  stat: path=/data/origin/_output/local/bin/linux/amd64/openshift
  register: which_openshift

- name: Print info about building openshift|oc|oadm binaries
  debug:
    msg: "Now going to build OpenShift binaries from local origin, this takes a few minutes..."
  when: 'which_openshift.stat.exists == False'

- name: When LOCAL_BUILD, need to install golang, takes a few minutes
  yum:
    name: golang
    state: present
  when: 'which_openshift.stat.exists == False'

- name: Build origin binaries
  shell:
    cmd: make
    chdir: /data/origin
  when: 'which_openshift.stat.exists == False'

# If setup was used to launch from copr rpm, and then with LOCAL_BUILD, the PATH won't be set
# correctly in the ec2, so need this to be sure:
- name: Make sure PATH is set correctly for non-local-build setup
  lineinfile: dest=/etc/profile.d/openshift.sh state=present regexp='^(.*)PATH' line='export PATH=/data/origin/_output/local/bin/linux/amd64:/bin:/usr/local/sbin:/sbin:/bin:/usr/sbin:/usr/bin:/root/bin:/root/bin'

- name: Creates /etc/systemd/system/origin-master.service.d directory
  file: path=/etc/systemd/system/origin-master.service.d state=directory

- name: Creates /etc/systemd/system/origin-node.service.d directory
  file: path=/etc/systemd/system/origin-node.service.d state=directory

- name: Create override.conf for origin-master.service
  blockinfile:
    dest: /etc/systemd/system/origin-master.service.d/override.conf
    create: yes
    content: |
      [Service]
      ExecStart=
      ExecStart=/data/origin/_output/local/bin/linux/amd64/openshift start master --config=${CONFIG_FILE} $OPTIONS

- name: Create override.conf for origin-node.service
  blockinfile:
    dest: /etc/systemd/system/origin-node.service.d/override.conf
    create: yes
    content: |
      [Service]
      ExecStart=
      ExecStart=/data/origin/_output/local/bin/linux/amd64/openshift start node --config=${CONFIG_FILE} $OPTIONS

- name: restart openshift services
  command: "{{ item }}"
  with_items:
    - systemctl daemon-reload
    - systemctl restart origin-master
    - systemctl restart origin-node


