---
- debug:
    msg: "OS - {{ os }}"

- name: Check for openshift command
  shell:
    cmd: "which openshift || :"
  register: which_openshift

- name: Remove /data/src/github.com/openshift/origin_output from PATH if not LOCAL_BUILD and the binary directory exists
  lineinfile: dest=/etc/profile.d/openshift.sh state=present regexp='^(.*)PATH' line='export PATH=/bin:/usr/local/sbin:/sbin:/bin:/usr/sbin:/usr/bin:/root/bin:/root/bin'
  when: '"/data/src/github.com/openshift/origin/_output/local/bin/linux/amd64" in which_openshift.stdout and not from_local_origin'

- name: start, enable NetworkManager
  command: "{{ item }}"
  with_items:
    - "systemctl enable NetworkManager"
    - "systemctl start NetworkManager"
  when: os == "centos7"
